default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: specials_development

test:
  <<: *default
  database: specials_test

production:
  <<: *default
  database: specials_production
  username: specials
  password: <%= ENV['SPECIALS_DATABASE_PASSWORD'] %>
